# Generated by Django 2.2 on 2021-05-19 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('gender_status', models.IntegerField(choices=[(1, 'BOY'), (2, 'GIRL')])),
                ('anonym_status', models.IntegerField(choices=[(1, 'PUBLIC'), (2, 'ANONYM')])),
                ('social_status', models.IntegerField(choices=[(1, 'CHILDREN_WITH_SPECIAL_NEEDS'), (2, 'ORPHAN'), (3, 'LARGE_FAMILY'), (4, 'LOW_INCOME_FAMILY'), (5, 'DISABLED'), (6, 'NIET_FUND')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('last_payment_day', models.DateTimeField(blank=True, default=None, null=True)),
                ('payment_count', models.IntegerField(default=0)),
                ('parents', models.TextField(blank=True, default=None, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('characteristics', models.TextField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Beneficary',
                'verbose_name_plural': 'Beneficaries',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('certificate_amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('program', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(null=True)),
                ('issued_state', models.IntegerField(choices=[(1, 'CREATED'), (2, 'GIVEN')], default=1)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='DefaultDonationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('sum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Default donation denominations',
                'verbose_name_plural': 'Default donation denominations',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('donation_amount', models.FloatField(null=True)),
                ('certificate_amount', models.FloatField(null=True)),
                ('donation_status', models.IntegerField(choices=[(1, 'PAYED'), (2, 'PENDING')], default=2)),
                ('donation_anonymous_state', models.IntegerField(choices=[(1, 'ANONYM'), (2, 'PUBLIC')], default=2)),
                ('donation_type', models.IntegerField(choices=[(1, 'COMMON'), (2, 'ZAKYAT')], default=1)),
                ('guest', models.BooleanField(default=False)),
                ('donation_automatic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='DonorRecurringProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('recurring_period', models.IntegerField(choices=[(1, 'WEEK'), (2, 'MONTH'), (3, 'QUARTER')])),
                ('recurring_profile_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('recurring_period_expire_date', models.CharField(default=None, max_length=255)),
                ('active_status', models.IntegerField()),
                ('in_processing', models.IntegerField(default=None)),
                ('last_transaction', models.TimeField(default=None, null=True)),
                ('next_transaction', models.TimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Donor recurring profile',
                'verbose_name_plural': 'Donor recurring profiles',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('gift_counts', models.IntegerField(null=True)),
                ('comment', models.TextField()),
                ('gift_image', models.ImageField(null=True, upload_to='gift_images')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='program_images')),
                ('icon2', models.ImageField(blank=True, default=None, null=True, upload_to='program_images')),
                ('poster', models.ImageField(blank=True, default=None, null=True, upload_to='program_images')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('order_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('title', models.CharField(default='Пожертвование', max_length=255, null=True)),
                ('payment_description', models.CharField(default='Пожертвование', max_length=255)),
                ('payment_url', models.TextField(default=' ', null=True)),
                ('payment_result_url', models.TextField(default=' ', null=True)),
                ('payment_id_paybox', models.CharField(default='0', max_length=255)),
                ('payment_status', models.IntegerField(choices=[(1, 'CREATED_PAYMENT'), (2, 'PAYMENT_PENDING_PAYBOX'), (3, 'PAYMENT_EXPIRED'), (4, 'PAYMENT_PAYED'), (5, 'SYSTEM_ERROR')], default=1)),
                ('payment_paybox_result', models.CharField(default='none', max_length=255, null=True)),
                ('payment_date', models.CharField(default='', max_length=255, null=True)),
                ('payment_signature', models.CharField(default='', max_length=255, null=True)),
                ('donation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Donation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PartnerProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.City')),
            ],
            options={
                'verbose_name': 'Partner program',
                'verbose_name_plural': 'Partner programs',
            },
        ),
    ]
