# Generated by Django 2.2 on 2021-05-19 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Partner'),
        ),
        migrations.AddField(
            model_name='gift',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Beneficary'),
        ),
        migrations.AddField(
            model_name='gift',
            name='partner_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.PartnerProgram'),
        ),
        migrations.AddField(
            model_name='donorrecurringprofile',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='beneficiaries',
            field=models.ManyToManyField(null=True, related_name='beneficiaries', to='donations.BeneficiaryAmount'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Program'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Beneficary'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Donation'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='partner_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.PartnerProgram'),
        ),
        migrations.AddField(
            model_name='beneficiaryamount',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Beneficary'),
        ),
        migrations.AddField(
            model_name='beneficary',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utility.City'),
        ),
        migrations.AddField(
            model_name='beneficary',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.Program'),
        ),
    ]
